apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  labels:
    app: bootcampapp
data:
  port: '80'
  host: '0.0.0.0'
  pgdatabase: 'weightracker'
  pgport: '5432'
  hosturl: 'http://20.81.22.73' # External IP of ingress-nginx-controller
  oktaurl: 'https://dev-16863907.okta.com'