apiVersion: v1
    kind: Secret
    metadata:
      name: app-secrets
      labels:
        app: bootcampapp
    data:
      pghost: wt-psqlserver-k8swt.postgres.database.azure.com
      pgusername: postgres
      pgpassword: p@ssw0rd42
      cookie_encrypt: superAwesomePasswordStringThatIsAtLeast32CharactersLong!
      oktaclient: 0oa3zcjl3fVulrBxA5d7
      oktasecret: 7EUvOmrvAiq_1won3dFSZ7Pph-5v8koocvh_zF_a